// submit-report — creates a report on behalf of the signed-in citizen.
// Validates input, requires an already-uploaded photo in the caller's own
// storage folder (FR-011), inserts the report (reference generated by DB
// trigger) plus the initial Submitted transition, and returns the new row.
import { createClient } from 'jsr:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const CATEGORIES = ['dumping', 'drain', 'streetlight'];

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405);

  // identify the caller from their JWT
  const userClient = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_ANON_KEY')!,
    { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } },
  );
  const { data: { user } } = await userClient.auth.getUser();
  if (!user) return json({ error: 'not signed in' }, 401);

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return json({ error: 'invalid JSON body' }, 400);
  }

  const category = body.category as string;
  const locationName = (body.location_name as string ?? '').trim();
  const description = (body.description as string ?? '').trim();
  const lat = Number(body.lat);
  const lng = Number(body.lng);
  const photoPath = body.photo_path as string;

  if (!CATEGORIES.includes(category)) return json({ error: 'invalid category' }, 400);
  if (!locationName || locationName.length > 120) return json({ error: 'invalid location_name' }, 400);
  if (description.length > 2000) return json({ error: 'description too long' }, 400);
  // loose Greater Accra bounding box
  if (!Number.isFinite(lat) || !Number.isFinite(lng) || lat < 4 || lat > 12 || lng < -4 || lng > 2) {
    return json({ error: 'invalid coordinates' }, 400);
  }
  // photo is mandatory and must live in the caller's own storage folder
  if (typeof photoPath !== 'string' || !new RegExp(`^${user.id}/[\\w.-]+$`).test(photoPath)) {
    return json({ error: 'photo required (upload it to your folder first)' }, 400);
  }

  const admin = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  // the photo must actually exist
  const { error: photoErr } = await admin.storage.from('report-photos').createSignedUrl(photoPath, 60);
  if (photoErr) return json({ error: 'photo not found in storage' }, 400);

  const { data: report, error: insertErr } = await admin
    .from('reports')
    .insert({
      category,
      description,
      location: `SRID=4326;POINT(${lng} ${lat})`,
      location_name: locationName,
      photo_urls: [photoPath],
      reporter_id: user.id,
    })
    .select()
    .single();
  if (insertErr) return json({ error: insertErr.message }, 500);

  const { error: transitionErr } = await admin.from('status_transitions').insert({
    report_id: report.id,
    from_status: null,
    to_status: 'submitted',
    actor_id: user.id,
    actor_role: 'citizen',
  });
  if (transitionErr) {
    // keep the closed loop honest: no report without its audit row
    await admin.from('reports').delete().eq('id', report.id);
    return json({ error: transitionErr.message }, 500);
  }

  return json({ report });
});
