// submit-report — creates a report on behalf of the signed-in citizen.
// Validates input, requires an already-uploaded photo in the caller's own
// storage folder (FR-011), inserts the report (reference generated by DB
// trigger) plus the initial Submitted transition, and returns the new row.
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { classifyAndEmbed } from '../_shared/image-model.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const CATEGORIES = ['dumping', 'drain', 'streetlight'];

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

// chunked to avoid blowing the call stack on String.fromCharCode(...bytes) for larger photos
function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return btoa(binary);
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405);

  // identify the caller from their JWT
  const userClient = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_ANON_KEY')!,
    { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } },
  );
  const { data: { user } } = await userClient.auth.getUser();
  if (!user) return json({ error: 'not signed in' }, 401);

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return json({ error: 'invalid JSON body' }, 400);
  }

  const category = body.category as string;
  const locationName = (body.location_name as string ?? '').trim();
  const description = (body.description as string ?? '').trim();
  const lat = Number(body.lat);
  const lng = Number(body.lng);
  const photoPaths = body.photo_paths as unknown;

  if (!CATEGORIES.includes(category)) return json({ error: 'invalid category' }, 400);
  if (!locationName || locationName.length > 120) return json({ error: 'invalid location_name' }, 400);
  if (description.length > 2000) return json({ error: 'description too long' }, 400);
  // loose Greater Accra bounding box
  if (!Number.isFinite(lat) || !Number.isFinite(lng) || lat < 4 || lat > 12 || lng < -4 || lng > 2) {
    return json({ error: 'invalid coordinates' }, 400);
  }
  // at least one photo is mandatory (FR-011), capped at 5; each must live in the
  // caller's own storage folder
  const MAX_PHOTOS = 5;
  const ownFolder = new RegExp(`^${user.id}/[\\w.-]+$`);
  if (!Array.isArray(photoPaths) || photoPaths.length < 1 || photoPaths.length > MAX_PHOTOS) {
    return json({ error: `1-${MAX_PHOTOS} photos required` }, 400);
  }
  if (!photoPaths.every((p) => typeof p === 'string' && ownFolder.test(p))) {
    return json({ error: 'photo required (upload it to your folder first)' }, 400);
  }
  const paths = photoPaths as string[];

  const admin = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  // every photo must actually exist in storage
  for (const p of paths) {
    const { error: photoErr } = await admin.storage.from('report-photos').createSignedUrl(p, 60);
    if (photoErr) return json({ error: 'photo not found in storage' }, 400);
  }

  // Authoritative embedding for check-duplicates (milestone 5): recomputed here
  // from the verified stored photo (not trusted from the client), via the
  // team's image model. Driven by the first photo (one embedding per report).
  // A photo the model can't process must never block report submission.
  let embedding: number[] | null = null;
  try {
    const { data: photoBlob, error: dlErr } = await admin.storage.from('report-photos').download(paths[0]);
    if (!dlErr && photoBlob) {
      const bytes = new Uint8Array(await photoBlob.arrayBuffer());
      const result = await classifyAndEmbed(bytesToBase64(bytes), photoBlob.type || 'image/webp');
      embedding = result.embedding;
    }
  } catch (e) {
    console.error('embedding computation failed (non-fatal):', e);
  }

  // ai_suggested_category/ai_confidence are supplementary evaluation metadata
  // (computed client-side via classify-image before submission) — validate
  // loosely and drop silently rather than rejecting the whole submission.
  let aiSuggestedCategory: string | null = null;
  let aiConfidence: number | null = null;
  if (CATEGORIES.includes(body.ai_suggested_category as string)) {
    aiSuggestedCategory = body.ai_suggested_category as string;
    const rawConfidence = Number(body.ai_confidence);
    if (Number.isFinite(rawConfidence) && rawConfidence >= 0 && rawConfidence <= 1) {
      aiConfidence = rawConfidence;
    }
  }

  const { data: report, error: insertErr } = await admin
    .from('reports')
    .insert({
      category,
      description,
      location: `SRID=4326;POINT(${lng} ${lat})`,
      location_name: locationName,
      photo_urls: paths,
      reporter_id: user.id,
      embedding,
      ai_suggested_category: aiSuggestedCategory,
      ai_confidence: aiConfidence,
    })
    .select()
    .single();
  if (insertErr) return json({ error: insertErr.message }, 500);

  const { error: transitionErr } = await admin.from('status_transitions').insert({
    report_id: report.id,
    from_status: null,
    to_status: 'submitted',
    actor_id: user.id,
    actor_role: 'citizen',
  });
  if (transitionErr) {
    // keep the closed loop honest: no report without its audit row
    await admin.from('reports').delete().eq('id', report.id);
    return json({ error: transitionErr.message }, 500);
  }

  return json({ report });
});
