// submit-report — creates a report on behalf of the signed-in citizen.
// Validates input, requires an already-uploaded photo in the caller's own
// storage folder (FR-011), inserts the report (reference generated by DB
// trigger) plus the initial Submitted transition, and returns the new row.
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { submitToCvApi, cvApiConfigured } from '../_shared/image-model.ts';
import { pointInAwma } from '../_shared/awma-boundary.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const CATEGORIES = [
  'dumping', 'drain', 'streetlight',
  'flooding', 'pothole', 'pollution', 'broken_public_facility', 'sanitation', 'other',
];
// Categories the CV model can't reliably confirm visually, so we never let its
// "not environmental" verdict block them: streetlight (no CV class) and other
// (an explicit catch-all for issues the model isn't expected to recognise).
const CV_VALIDITY_EXEMPT = ['streetlight', 'other'];

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405);

  // identify the caller from their JWT
  const userClient = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_ANON_KEY')!,
    { global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } } },
  );
  const { data: { user } } = await userClient.auth.getUser();
  if (!user) return json({ error: 'not signed in' }, 401);

  let body: Record<string, unknown>;
  try {
    body = await req.json();
  } catch {
    return json({ error: 'invalid JSON body' }, 400);
  }

  const category = body.category as string;
  const locationName = (body.location_name as string ?? '').trim();
  const description = (body.description as string ?? '').trim();
  const lat = Number(body.lat);
  const lng = Number(body.lng);
  const photoPaths = body.photo_paths as unknown;

  if (!CATEGORIES.includes(category)) return json({ error: 'invalid category' }, 400);
  if (!locationName || locationName.length > 120) return json({ error: 'invalid location_name' }, 400);
  if (description.length > 2000) return json({ error: 'description too long' }, 400);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) {
    return json({ error: 'invalid coordinates' }, 400);
  }
  // jurisdiction gate: the pilot only serves Ayawaso West Municipal Assembly, so
  // reject any point outside AWMA's boundary (polygon + ~500 m tolerance). This is
  // the authoritative check — the citizen app also warns/blocks, but the server is
  // the source of truth (clients never place a report outside jurisdiction).
  if (!pointInAwma(lat, lng)) {
    return json({
      error: 'This location is outside Ayawaso West Municipal Assembly. Reports must be inside the municipality.',
      code: 'outside_awma',
    }, 422);
  }
  // at least one photo is mandatory (FR-011), capped at 5; each must live in the
  // caller's own storage folder
  const MAX_PHOTOS = 5;
  const ownFolder = new RegExp(`^${user.id}/[\\w.-]+$`);
  if (!Array.isArray(photoPaths) || photoPaths.length < 1 || photoPaths.length > MAX_PHOTOS) {
    return json({ error: `1-${MAX_PHOTOS} photos required` }, 400);
  }
  if (!photoPaths.every((p) => typeof p === 'string' && ownFolder.test(p))) {
    return json({ error: 'photo required (upload it to your folder first)' }, 400);
  }
  const paths = photoPaths as string[];

  const admin = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  // every photo must actually exist in storage
  for (const p of paths) {
    const { error: photoErr } = await admin.storage.from('report-photos').createSignedUrl(p, 60);
    if (photoErr) return json({ error: 'photo not found in storage' }, 400);
  }

  // AI features (milestone 5): the external CV service classifies the photo,
  // dedupes it against its own corpus, and validates it's a genuine
  // environmental concern. We drive it from the first (main) photo, from the
  // verified stored copy — never trusting AI metadata from the client.
  //
  // Two failure modes are handled differently:
  //  - the CV service says the photo is NOT an environmental concern (a selfie
  //    or junk) -> block submission with a retake message (input validation).
  //  - the CV service is unreachable / errors -> fail soft: create the report
  //    with no AI metadata. An outage must never halt civic reporting.
  let externalReportId: number | null = null;
  let aiSuggestedCategory: string | null = null;
  let aiConfidence: number | null = null;
  let duplicateStatus: string | null = null;
  let detectedObjects: unknown[] | null = null;
  let perceptualHash: string | null = null;

  // "mine is different" re-submission after a duplicate was detected: the citizen
  // overrode the AI suggestion, so skip the CV block entirely (which both detects
  // AND registers the image — re-running it would double-register). The report is
  // created with null AI metadata, exactly like the CV-outage fail-soft path.
  const forceCreate = body.force_create === true;

  // The CV service says a photo is a strong duplicate; only 'duplicate' (not the
  // looser 'possible_duplicate') triggers the citizen-facing follow offer.
  const STRONG_DUPLICATE = 'duplicate';

  if (cvApiConfigured() && !forceCreate) {
    try {
      const { data: photoBlob, error: dlErr } = await admin.storage.from('report-photos').download(paths[0]);
      if (!dlErr && photoBlob) {
        const bytes = new Uint8Array(await photoBlob.arrayBuffer());
        const cv = await submitToCvApi({
          imageBytes: bytes,
          mimeType: photoBlob.type || 'image/webp',
          category,
          title: description || `${category} at ${locationName}`,
          description,
          lat,
          lng,
        });
        // Validity-gate safeguard: the CV model has no streetlight class (and
        // "other" is a deliberate catch-all), so it may wrongly reject a valid
        // photo as "not environmental" for those; ignore that verdict for the
        // exempt categories (see image-model.ts and CV_VALIDITY_EXEMPT above).
        if (cv.verdict === 'not_environmental' && !CV_VALIDITY_EXEMPT.includes(category)) {
          return json({
            error: "This photo doesn't look like a civic issue. Please retake it showing the problem clearly.",
            code: 'photo_not_environmental',
          }, 422);
        }
        externalReportId = cv.externalId;
        aiSuggestedCategory = cv.cvCategory;
        aiConfidence = cv.cvConfidence;
        duplicateStatus = cv.duplicateStatus;
        detectedObjects = cv.detectedObjects;
        perceptualHash = cv.perceptualHash;

        // Strong-duplicate follow offer: the CV service says this photo duplicates
        // an existing report. If that report maps to one of OUR rows (via the CV
        // integer id -> external_report_id reverse map, same as check-duplicates)
        // and isn't the citizen's own, do NOT create a report — return the
        // candidate so the client can offer "follow it" vs "submit anyway".
        // The uploaded photos stay in storage: follow-report cleans them up on the
        // follow path, or a force_create re-call reuses them on the decline path.
        if (duplicateStatus === STRONG_DUPLICATE && cv.duplicateOfExternalId != null) {
          const { data: candidate } = await admin
            .from('reports')
            .select('id, reference, category, location_name, status, follower_count, reporter_id')
            .eq('external_report_id', cv.duplicateOfExternalId)
            .maybeSingle();
          if (candidate && candidate.reporter_id !== user.id) {
            // record that we offered this candidate to this user, so follow-report
            // can verify the follow is legitimate (guards against following an
            // arbitrary report_id — see 20260720123000_duplicate_offers.sql).
            await admin
              .from('duplicate_offers')
              .upsert({ user_id: user.id, report_id: candidate.id }, { onConflict: 'user_id,report_id', ignoreDuplicates: true });
            return json({
              status: 'duplicate_detected',
              candidate: {
                id: candidate.id,
                reference: candidate.reference,
                category: candidate.category,
                location_name: candidate.location_name,
                status: candidate.status,
                follower_count: candidate.follower_count,
              },
            });
          }
          // candidate missing (older/CV-only row) or it's the caller's own report:
          // fall through and create the report normally.
        }
      }
    } catch (e) {
      console.error('CV API call failed (non-fatal, submission proceeds):', e);
    }
  }

  const { data: report, error: insertErr } = await admin
    .from('reports')
    .insert({
      category,
      description,
      location: `SRID=4326;POINT(${lng} ${lat})`,
      location_name: locationName,
      photo_urls: paths,
      reporter_id: user.id,
      external_report_id: externalReportId,
      ai_suggested_category: aiSuggestedCategory,
      ai_confidence: aiConfidence,
      duplicate_status: duplicateStatus,
      detected_objects: detectedObjects,
      perceptual_hash: perceptualHash,
    })
    .select()
    .single();
  if (insertErr) return json({ error: insertErr.message }, 500);

  const { error: transitionErr } = await admin.from('status_transitions').insert({
    report_id: report.id,
    from_status: null,
    to_status: 'submitted',
    actor_id: user.id,
    actor_role: 'citizen',
  });
  if (transitionErr) {
    // keep the closed loop honest: no report without its audit row
    await admin.from('reports').delete().eq('id', report.id);
    return json({ error: transitionErr.message }, 500);
  }

  return json({ report });
});
